deployment:
  tasks:
    - export DEPLOYPATH=/home/kvthsnjw/d3sia4703-1.produkd3sia.com
    - cd $DEPLOYPATH
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache